### PR TITLE
Created .gitignore, linters.yml, html, css and updating readme.md

### PR DESCRIPTION
**Pull request by evillaz**
This branch's purpose was to fill the requirements for the activity such as. 
Created the .gitignore file to ignore node_modules and "test.md" files when the "git status" command check on the changes for a new commit.
Created linters.yml, to implement the linters to our project so it could flag patterns that might cause errors or other problems to the project
create the HTML file with the header asked on the requirement and the CSS styling to change the text color for it. 
Also changed the readme file to a more accurate one following the template. 
And also added a LICENSE.md file to it. 
the previous PR was https://github.com/evillaz/hello-microverse-review/pull/1.

### CODE REVIEW

**Review by Olamarx — CHANGES_REQUESTED** [review]
Hi @evillaz, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- Linters passed ✔️ 
- Commit messages ✔️ 

 ## Required Changes ♻️
_Check the comments under the review._
- [ ] As pointed out by the previous reviewer, your PR needs to be descriptive.  I would advise you to make a descriptive PR. A descriptive PR includes a descriptive title telling what changes are inside and a summary describing introduced changes in more detail.
- [ ] I see you removed most of the Readme content, you should not remove any, you should just replace it with your own content.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by evillaz** [comment]
@Olamarx hi thank you for your time reviewing my code I had a hard time trying to understand some of the changes. so what I understand is that I need to change the PR description for a more detailed one, and do you think I should change the PR's name as well or is it ok "Created gitignore linters HTML css files" because that pretty much summarizes what I did. Also, I'm going to edit the readme template as well.

**Comment by evillaz** [comment]
@Olamarx hi i did some changes as you asked for complete the review do you think the project is ready to ask a for a new review?

**Review by jerryowusu — APPROVED** [review]
Hi @evillaz , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

chelsea-mason-approve

## Highlights
All linters are passing :heavy_check_mark: 
Great effort so far :heavy_check_mark: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
